# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import config_pb2 as config__pb2


class MLServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.image_similarity = channel.stream_unary(
        '/MLServer/image_similarity',
        request_serializer=config__pb2.ImageBuffer.SerializeToString,
        response_deserializer=config__pb2.Reply.FromString,
        )


class MLServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def image_similarity(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MLServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'image_similarity': grpc.stream_unary_rpc_method_handler(
          servicer.image_similarity,
          request_deserializer=config__pb2.ImageBuffer.FromString,
          response_serializer=config__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MLServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
